### ISSUE TITLE
First argument of MongoDB\Laravel\Query\Builder::where must be a field path as "string". Got "null"

### ISSUE THREAD

**Issue by clarkeash** [jenssegers/laravel-mongodb#2725] opened 2024-02-12 17:35 UTC
- Laravel-mongodb Version: 4.1.1
- PHP Version: 8.3.2
- Database Driver & Version: 1.17.2

### Steps to reproduce
I have the following models (simplified for clarity)
```php
class Account extends Model {
public function stripe(): EmbedsOne
    {
        return $this->embedsOne(Stripe::class);
    }
}
```

```php
class Stripe extends Model {}
```

Then when I try to update the stripe subdocument like so:
```php
$account = Account::find(...);
$stripe = $account->stripe;
$stripe->subscription = ['some data'];
$stripe->save();
```

### Expected behaviour
Tell us what should happen `jenssegers/mongodb` 3.9 it would save the data just fine.

### Actual behaviour
```
1) Tests\Feature\Actions\Stripe\CancelPendingChangeTest::it_will_cancel_a_pending_modification
InvalidArgumentException: First argument of MongoDB\Laravel\Query\Builder::where must be a field path as "string". Got "null"

/Users/clarkeash/code/sites/billing/vendor/mongodb/laravel-mongodb/src/Query/Builder.php:1012
/Users/clarkeash/code/sites/billing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:302
/Users/clarkeash/code/sites/billing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1254
/Users/clarkeash/code/sites/billing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1213
/Users/clarkeash/code/sites/billing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1130
/Users/clarkeash/code/sites/billing/vendor/mongodb/laravel-mongodb/src/Eloquent/Model.php:737
/Users/clarkeash/code/sites/billing/app/Actions/Stripe/StoreSubscriptionInformation.php:82
/Users/clarkeash/code/sites/billing/vendor/lorisleiva/laravel-actions/src/Concerns/AsObject.php:24
/Users/clarkeash/code/sites/billing/tests/Feature/Actions/Stripe/CancelPendingChangeTest.php:41
```

I am unsure if this is a bug or if I have missed something, can you point me in the right direction? Thanks

**Comment by GromNaN** [comment] 2024-02-12 20:24
Hi, we have a [test for the embedOne feature](https://github.com/mongodb/laravel-mongodb/blob/cff277384ca0d8da45663c00a494ea84cafd0459/tests/EmbeddedRelationsTest.php#L543), but it seems that your use-case is not covered. 

Tracking this issue in Jira to investigate. [PHPORM-144](https://jira.mongodb.org/browse/PHPORM-144)

**Comment by GromNaN** [comment] 2024-02-13 13:57
This exception was introduced in #2642 [063d73f](https://github.com/mongodb/laravel-mongodb/commit/063d73ff2a9284e6a5b561544a94213a2ea8bb2a#diff-bdf045bbd1faa398417a788236b3b7da49c553bc4c6e7d6403568ecd775d2034R990-R991)

I've been unable to reproduce the bug by creating a model similar to yours.

**Comment by clarkeash** [comment] 2024-02-15 11:56
Strange, I will try and put together a reproducible case for you

**Comment by GromNaN** [comment] 2024-02-27 14:36
Hi @clarkeash, were you able to find a reproducer?

**Comment by GromNaN** [comment] 2024-03-05 14:23
Closing as I can't reproduce. I can reopen if you can provide a reproducer.

**Closed as not planned by GromNaN** 2024-03-05 14:23 UTC
Labels: awaiting-author, tracked-in-jira

**Comment by clarkeash** [comment] 2024-03-08 10:34
Okay fair enough, I have not had the time to reproduce it as I have a workaround.
