### ISSUE TITLE
Class 'Jenssegers\Mongodb\Eloquent\Model' not found

### ISSUE THREAD

**Issue by omerolmez** [jenssegers/laravel-mongodb#2052] opened 2020-06-17 14:23 UTC
- Laravel Version: 7.16.1
- PHP Version: 7.4
- Database Driver & Version: "jenssegers/mongodb": "4.0.0-alpha.1"

I have a queue application that I call from the console. When I want to insert collection I am getting bellow error. What would be the reason? I think bug.

` Class 'Jenssegers\Mongodb\Eloquent\Model' not found {"exception":"[object] (Error(code: 0): Class 'Jenssegers\\Mongodb\\Eloquent\\Model' not found `

When I use normal on browser. Its okay. 

I made "composer dump-autoload" but not changed anything.

**Comment by divine** [comment] 2020-06-17 15:00
Hi,

Have you configured your queues correctly ?
See https://github.com/jenssegers/laravel-mongodb#queues

Thanks.

**Comment by omerolmez** [comment] 2020-06-17 16:24
not related to it. my queue working with Redis. But I have eloquent listener (created).  

```
<?php

namespace App\Listeners;

use App\Http\Controllers\Common\Models\ActivityLogs;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;

class EloquentListener
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  Logout  $event
     * @return void
     */
    public function handle($event, $data)
    {
        $disableFire = [
            'ActivityLogs'
        ];

        $continue = true;
        foreach ($disableFire as $item) {
            $continue = strstr($event, $item) ? false: true;
        }

        if ($continue) {
            ActivityLogs::create([
                'fire_event' => $event,
                'user_id' => auth()->id(),
                'site_id' => auth()->user()->site_id
            ]);
        }

        return true;

    }

}
```
My model is below:

```
<?php

namespace App\Http\Controllers\Common\Models;

use Jenssegers\Mongodb\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\SoftDeletes;

class ActivityLogs extends Model {

    use SoftDeletes;

    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    protected $collection = 'activity_logs';

    protected $connection = 'mongodb';

    protected $fillable = [
        //'activity_log_id',
        'fire_event',
        'site_id',
        'user_id',
        'deleted_at',
        'created_at',
        'updated_at'
    ];
}

```
When I work cli (php artisan queue:work) I am getting Class 'Jenssegers\Mongodb\Eloquent\Model' not found

**Comment by Smolevich** [comment] 2020-06-17 20:15
@omerolmez  looks like problem autoloading class `Jenssegers\Mongodb\Eloquent\Model`
Check `vendor/composer/autoload_classmap.php` file on existing mapping 
See
<img width="1011" alt="Снимок экрана 2020-06-17 в 23 14 19" src="https://user-images.githubusercontent.com/7188867/84945808-63217c80-b0f0-11ea-899e-48b4a1ff9d3a.png">

**Comment by omerolmez** [comment] 2020-06-17 20:20
there is inside autoload_classmap.php . I think I could tell. Problem is on cli.

**Comment by Smolevich** [comment] 2020-06-17 20:29
Cli should use same vendor, it don't affect discovering class. Do you have problems with another dependencies in running `queue: work` ?

**Comment by omerolmez** [comment] 2020-06-17 20:32
Thank you.

No I dont have any problem. Only this.

**Comment by Smolevich** [comment] 2020-06-18 07:35
@omerolmez see https://github.com/Smolevich/demo-mongo-application/pull/27

**Comment by omerolmez** [comment] 2020-06-18 08:06
@Smolevich what is this? I do not understand.

**Comment by Smolevich** [comment] 2020-06-18 08:09
I implemented your listener

**Comment by Smolevich** [comment] 2020-06-18 08:10
You can run docker-compose configuration in this repo and check correct work

**Comment by omerolmez** [comment] 2020-06-18 09:29
is it working cli?

**Comment by Smolevich** [comment] 2020-06-18 09:31
> is it working cli?

Yes

**Comment by omerolmez** [comment] 2020-06-18 09:50
Thanks. 

But I am using:
"laravel/framework": "7.16.1"
PHP Version: 7.4
Database Driver & Version: "jenssegers/mongodb": "4.0.0-alpha.1"

Your version:
"jenssegers/mongodb": "dev-master",
"laravel/framework": "^6.2",

Everything is normal in my project.

**Comment by Smolevich** [comment] 2020-06-18 10:04
https://github.com/Smolevich/demo-mongo-application/blob/6d4b9605501d1d1803f33ee602258c0c12fb1b17/composer.lock#L464 laravel 7.16.1
https://github.com/Smolevich/demo-mongo-application/blob/6d4b9605501d1d1803f33ee602258c0c12fb1b17/composer.lock#L395 - 4.0.0-alpha.1"

**Comment by divine** [comment] 2020-06-18 14:45
I can't reproduce myself too.

**Comment by divine** [comment] 2020-06-24 03:07
Closing. Please let us know when you'll have more information to share.

Thanks!

**Closed by divine** 2020-06-24 03:07 UTC
Labels: Needs investigation, question

**Comment by shifas05** [comment] 2022-01-14 06:00
I have this same issue for me this is happening only in server, Its a command to insert data to mongo db, Iam getting this below error when executing the command in server.
```

Unhandled error
Error: Class 'Jenssegers\Mongodb\Eloquent\Model' not found
```


Sample code 

`
namespace App\Console\Commands\PropertyActivities;

use App\Models\MongoDb\Collections\PropertyActivity;

class LogExistingPropertyActivities extends Command
{
   $dataToStoreToMongoDb = [
                                                    ['property_address'=>'xxxx', 'zip' => 'xxx'], 
                                                    ['property_address'=>'xxxx', 'zip' => 'xxx']
                                                 ];

   PropertyActivity::query()->insert($queryValueStrings);

}

`
