### ISSUE TITLE
updateOrCreate -> createOrFirst doesn't work as expected

### ISSUE THREAD

**Issue by Boevsson** [jenssegers/laravel-mongodb#2945] opened 2024-05-14 11:13 UTC
- Laravel-mongodb Version: 4.2
- PHP Version: 8.3.4
- Database Driver & Version: mongod 5.0 / 7.0

### Steps to reproduce
1. $id = $request->get('id') ?? null; // in the case id is null
2. Do `Model::updateOrCreate(['_id' => $id], $data);`

### Expected behaviour

A new record should be created with the given data and a generated _id.

### Actual behaviour

It queries the first record from the collection and updates it.

This works fine when using the package 4.0 because the createOrFirst is not overriden there in the Mongo Builder class

**Comment by GromNaN** [comment] 2024-05-20 10:46
Thanks for the report.
Related to #2935
~Tracked in Jira PHPORM-183~

**Comment by GromNaN** [comment] 2024-05-22 15:08
After investigation, `null` is a valid value for MongoDB `_id`. That's why the `Model::updateOrCreate(['_id' => null], $data)` creates or updates a new document with `_id: null`.

This is inconsistent with how SQL works because SQL databases will generate a value with a request like this: `INSERT INTO table (id, name) VALUES (null, 'foo')`.

Can you modify your code like this:

```php
$id = $request->get('id'); // null is the default value
if ($id) {
    $model = Model::updateOrCreate(['_id' => $id], $data);
} else {
    $model = Model::create($data);
}
```

**Comment by GromNaN** [comment] 2024-05-28 09:31
Closing as this is the expected behavior for MongoDB.

**Closed as not planned by GromNaN** 2024-05-28 09:31 UTC
Labels: tracked-in-jira
