### ISSUE TITLE
How to use allowDiskUse: true?

### ISSUE THREAD

**Issue by sparrowbear** [jenssegers/laravel-mongodb#541] opened 2015-07-11 13:22 UTC
Help me,

How can I use 'allowDiskUse: true' in my model query?

**Comment by hackel** [comment] 2015-07-30 20:02
Dupe of #491. Not supported, but would be easy to add as an option in \Jenssegers\Mongodb\Query\Builder::getFresh.

**Comment by chloealee** [comment] 2015-08-20 20:30
Having the same issue! @hackel do you mean it'd be an easy fix on jenssegers end or would anyone be able to add code into their app for it to work? If the latter, could you explain how?

**Comment by hackel** [comment] 2015-09-18 20:25
@chloealee You would have to fork it and modify the getFresh method.  This is where MongoCollection::aggregate() is called, and allowDiskUse needs to be passed as an option there.  If you don't want to bother with forking, you can just create a raw query with the raw() method.

**Comment by chloealee** [comment] 2015-09-21 14:01
@hackel great, thanks!

**Comment by chloealee** [comment] 2015-09-23 20:48
@hackel still having some trouble - tried to insert it into my raw query (below) but getting this error: 

`[MongoResultException]
  localhost:27017: exception: Unrecognized pipeline stage name: 'allowDiskUse'`

```
        $duplicates = User::raw(function($collection) {
            return $collection->aggregate(
                [
                    '$group' => [
                        '_id' => ['email' => '$email'
                        ],
                        'uniqueIds' => [
                            '$addToSet' => '$_id'
                        ],
                        'count' => [
                            '$sum' => 1
                        ]
                    ]
                ],
                [
                    '$match' => [
                        'count' => [
                            '$gt' => 1
                        ]
                    ]
                ],
                [
                    'allowDiskUse' => true,
                    // 'cursor' => {}
                ]
            );
        });
```

do you know what I'm doing wrong?

**Comment by chloealee** [comment] 2015-09-24 15:26
I see what I did wrong now! If anyone is having this issue too and needs an example, got this to work: 

```
        $duplicates = User::raw(function($collection) {
            return $collection->aggregate(
                [
                    [
                        '$group' => [
                            '_id' => ['email' => '$email'
                            ],
                            'uniqueIds' => [
                                '$addToSet' => '$_id'
                            ],
                            'count' => [
                                '$sum' => 1
                            ]
                        ]
                    ],
                    [
                        '$match' => [
                            'count' => [
                                '$gt' => 1
                            ]
                        ]
                    ]
                ],
                [
                    'allowDiskUse' => true,
                ]
            );
        });
```

**Comment by ScottSpittle** [comment] 2015-09-24 15:33
How would you go about passing in values from outside $duplicates, such as an array to compare.

**Comment by chloealee** [comment] 2015-09-24 16:48
I think you'd want to do that after you find all of the $duplicates instead of passing through - just compare with the results in the array that gets returned.

**Comment by ScottSpittle** [comment] 2015-09-24 16:52
Yeah, but the index filtering results before they are returned would be a lot quicker

**Comment by chloealee** [comment] 2015-09-24 17:20
I'm not quite sure - sorry @ScottSpittle !

**Comment by ScottSpittle** [comment] 2015-09-25 06:31
@chloealee No worries, Thanks anyway.

**Comment by pi0** [comment] 2016-09-28 15:24
@sparrowbear @hackel @chloealee  
This issue is now fixed on [Moloquent Branch](https://github.com/moloquent/moloquent) :)

**Closed** 2016-09-28 15:42 UTC

**Comment by Puggers** [comment] 2018-04-05 14:42
Not sure if I am in the right place for this, I am attempting to add the AllowDiskUse option invoking the options function, it doesn't seem to be handling it. Is AllowDiskUse usable outside of a raw query? 
```
$tweets = Tweet::whereBetween('created_at.sec', dateToInt($request->get('startDate'), $request->get('endDate')))
            ->where(getTweets($request))
            ->orderBy('created_at.sec', 'desc')
            ->paginate(10)
            ->options(['AllowDiskUse' => true]);
```

**Comment by amjad-eremnews** [comment] 2018-07-05 07:48
@Puggers Can you please change `AllowDiskUse` to `allowDiskUse`?

**Comment by Puggers** [comment] 2018-07-26 15:56
@amjad-eremnews The power of cases... yup that did it. Thanks!
