### ISSUE TITLE
v3.2.1 created_at, and updated_at stored as 0.

### ISSUE THREAD

**Issue by azhard4int** [jenssegers/laravel-mongodb#1131] opened 2017-02-26 09:24 UTC
Hi,

After the recent update, the created_at and updated_at values are stored as shown below:

[updated_at] => MongoDate Object (
    [sec] => 0
    [usec] => 0
)
[created_at] => MongoDate Object (
    [sec] => 0
    [usec] => 0
)

**Comment by azhard4int** [comment] 2017-02-26 09:29
@jenssegers downgrading to v3.2.0 fixed the datetime issue, I am using laravel 5.3.

**Comment by jenssegers** [comment] 2017-02-26 10:58
Damn that is weird, I'll check it out.

**Comment by jenssegers** [comment] 2017-02-26 11:15
I'm not seeing this behaviour in my unit tests though

**Comment by staf** [comment] 2017-02-27 14:58
Can confirm this is happening for us as well in several of our projects after upgrading to 3.2.1

**Comment by azhard4int** [comment] 2017-02-27 16:29
@staf are you running php 7 or php 5?

**Comment by staf** [comment] 2017-02-27 16:31
I'm running 7. A coworker on 5.6 had the same issue. But a driver upgrade from 1.1 to 1.2 solved it in either case.

**Comment by mario-laserna** [comment] 2017-02-27 21:04
Hi, I am having a similar issue, dates (created_at, updated_at) of all models are saving like  ISODate("1970-01-01T00:00:00Z"), always this same date

I had to downgrade to 3.2.0 and all works fine again, I have this problem only in server (Ubuntu 14 and PHP 7.0) but not in my machine (win10, php7.0)

**Comment by acidjazz** [comment] 2017-02-28 03:40
confirmed, php7, both of my setups, laravel 5.4 and lumen 5.2, all 6 of my models

**Comment by domagala** [comment] 2017-03-01 12:01
Issue exists with PHP 7.0 and MongoDB 1.2.5 driver. Had to downgrade to 3.2.0 and its working.

**Comment by mario-laserna** [comment] 2017-03-02 13:10
@jenssegers this is happening now with version 3.2.0 on win10 also

**Comment by jenssegers** [comment] 2017-03-02 14:01
Could someone do a PR to revert the previous change to fix this issue?

**Comment by Endijs** [comment] 2017-03-08 12:53
I also had the same problem. Updated mongodb driver and problem was fixed. I'm using PHP 7. Those who experience this issue, try updating mongodb driver.

**Comment by acidjazz** [comment] 2017-03-08 17:32
@Endijs to what version? i always keep mine up to date

**Comment by Endijs** [comment] 2017-03-08 17:55
@acidjazz 
`
$ php -v
PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13-0ubuntu0.16.04.1, Copyright (c) 1999-2016, by Zend Technologies

$ php --ri mongodb

mongodb

MongoDB support => enabled
MongoDB extension version => 1.2.5
MongoDB extension stability => stable
libbson bundled version => 1.5.4
libmongoc bundled version => 1.5.4
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => disabled

`

**Comment by acidjazz** [comment] 2017-03-08 20:25
@Endijs you sure your dates are being stored correctly now? 

if this is the solution then @jenssegers can we somehow put a stipulation on this version to require that version of the php driver to help avoid this severe issue?

**Comment by Endijs** [comment] 2017-03-08 20:30
@acidjazz Well - for me it worked out (just like for @staf ). At least i can't spot any new records with 0 anymore.  However @domagala is also using 1.2.5 and is reporting that issue still persists. Thus it looks like sometimes that fixes the problem, but not always. Maybe something else is at play here. 
But it's good place to start for those who are having this issue. Try updating mongodb driver and report if that helps or not.

**Comment by divine** [comment] 2020-02-14 21:03
Closing, merged in #1148.

**Closed by divine** 2020-02-14 21:03 UTC
