### ISSUE TITLE
[Feature Request] Don't convert __id to objectID by default.

### ISSUE THREAD

**Issue by vacoup96** [jenssegers/laravel-mongodb#2076] opened 2020-08-10 07:45 UTC
### Is your feature request related to a problem?
I'm working with existing data and ObjectID are not used, it's just strings. 
If I have to use ObjectID's I have to update all existing data and the entire API. 

### Describe the solution you'd like
I would like to have the option to not use objectID's, or not even use a primary key. 

### Additional context
I believe the get and setAttribute functions are to blame. They have some pretty strange code inside. 

```
    /**
     * {@inheritdoc}
     */
    public function setAttribute($key, $value)
    {
        // Convert _id to ObjectID.
        if ($key == '_id' && is_string($value)) {
            $builder = $this->newBaseQueryBuilder();

            $value = $builder->convertKey($value);
        } // Support keys in dot notation.
        elseif (Str::contains($key, '.')) {
            if (in_array($key, $this->getDates()) && $value) {
                $value = $this->fromDateTime($value);
            }

            Arr::set($this->attributes, $key, $value);

            return;
        }

        return parent::setAttribute($key, $value);
    }
```

**Comment by vacoup96** [comment] 2020-08-10 11:34
Does anyone have any answer for me? Is this possible somehow? Even just as a temporary solution. I've tried overriding setAttribute method and when I dd Customer::create($customer) it seems to return the valid ID. However, when I look in the database, it has a different value so it's actually not saving that _id. Even looking through the whole package, I can't find how it's saving _id.

**Comment by Smolevich** [comment] 2020-08-10 12:09
@vacoup96 do you want have possibility don't use primary keys with type ObjectID?

**Comment by vacoup96** [comment] 2020-08-10 12:11
> @vacoup96 do you want have possibility don't use primary keys with type ObjectID?

Yes!

**Comment by Smolevich** [comment] 2020-08-10 12:22
https://docs.mongodb.com/manual/core/document/#the-id-field mongodb storage creates automatically index for `_id` field, if client doesn't send field `_id`

**Comment by vacoup96** [comment] 2020-08-10 12:43
> https://docs.mongodb.com/manual/core/document/#the-id-field mongodb storage creates automatically index for `_id` field, if client doesn't send field `_id`

Do you know if I can make it into a string instead of ObjectId?

**Comment by Smolevich** [comment] 2020-08-10 12:46
What is root cause ? What do you want to do?

**Comment by vacoup96** [comment] 2020-08-10 12:50
> What is root cause ? What do you want to do?

I have a lot of old data and an API that is generating strings as _id's. To change it would take me several weeks because it's so much.

**Comment by Smolevich** [comment] 2020-08-10 13:13
You can update all documents add new field with type string using (generate new ObjectId with castring string or copy from `_id`)https://docs.mongodb.com/manual/reference/operator/aggregation/toString/

**Comment by vacoup96** [comment] 2020-08-10 13:59
> You can update all documents add new field with type string using (generate new ObjectId with castring string or copy from `_id`)https://docs.mongodb.com/manual/reference/operator/aggregation/toString/

Do you have any exampleS? I can't get it done...

**Comment by divine** [comment] 2020-08-11 02:05
This is a duplicate of https://github.com/jenssegers/laravel-mongodb/issues/1761

Planned on version 4 https://github.com/jenssegers/laravel-mongodb/projects/2#card-33675919

Basically, we're having some huge problems with removal of auto-casting. See my explanation here: https://github.com/jenssegers/laravel-mongodb/issues/2023#issuecomment-615282098

**Comment by vacoup96** [comment] 2020-08-11 08:07
> This is a duplicate of #1761
> 
> Planned on version 4 https://github.com/jenssegers/laravel-mongodb/projects/2#card-33675919
> 
> Basically, we're having some huge problems with removal of auto-casting. See my explanation here: [#2023 (comment)](https://github.com/jenssegers/laravel-mongodb/issues/2023#issuecomment-615282098)

If anyone else needs to an immediate  fix for this issue, you can create a Model.php and a Builder.php. In your Model change the imported extend Model with your model and overwrite the newBaseQueryBuilder() function and add use App\Query\Builder as QueryBuilder in the top of your Model.php like this:

```
namespace App\Query;

use Jenssegers\Mongodb\Eloquent\Model as BaseModel;
use App\Query\Builder as QueryBuilder;

abstract class Model extends BaseModel
{
    /**
     * {@inheritdoc}
     */
    protected function newBaseQueryBuilder()
    {
        $connection = $this->getConnection();

        return new QueryBuilder($connection, $connection->getPostProcessor());
    }
}
```

Create your own Builder.php at the namespace of the use above. `use App\Query\Builder as QueryBuilder;` and then you can overwrite for example the insertGetId.... 

```
namespace App\Query;

use Illuminate\Support\Str;
use Jenssegers\Mongodb\Connection;
use Jenssegers\Mongodb\Query\Builder as BaseBuilder;
use Jenssegers\Mongodb\Query\Processor;

class Builder extends BaseBuilder
{
    private function createId()
    {
        return Str::random(32);
    }

    private function injectId(&$values)
    {
        return $values['_id'] = $this->createId();
    }
    /**
     * {@inheritdoc}
     */
    public function insertGetId(array $values, $sequence = null)
    {
        $this->injectId($values);
        $result = $this->collection->insertOne($values);

        if (1 == (int) $result->isAcknowledged()) {
            if ($sequence === null) {
                $sequence = '_id';
            }

            // Return id
            return $sequence == '_id' ? $result->getInsertedId() : $values[$sequence];
        }
    }

}
```

**Comment by divine** [comment] 2020-08-12 02:37
Great! Closing it up because it's a duplicate.

Thanks!

**Closed by divine** 2020-08-12 02:37 UTC
Labels: duplicate, enhancement
