### ISSUE TITLE
Softdelete Restore not firing

### ISSUE THREAD

**Issue by bradyounger** [jenssegers/laravel-mongodb#1008] opened 2016-10-31 01:56 UTC
Hi

I have just moved from MySQL to MongoDB and have everything working with this extension apart from the restore method of SoftDelete is not working. I'm not sure if I am looking in the right place (just new to MongoDB) but it appears this method is not firing.

Here is my model def:

<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Moloquent;
use Jenssegers\Mongodb\Eloquent\SoftDeletes;

class Account extends Moloquent
{
    protected $table = 'accounts';

```
use SoftDeletes;

/**
 * The attributes that should be mutated to dates.
 *
 * @var array
 */
protected $dates = ['deleted_at'];
```

}

And heres my restore controller method:

```
/**
 * restore deleted account
 *
 * @param  int  $id
 * @return \Illuminate\Http\Response
 */
public function restore($id)
{
    Account::withTrashed()
        ->where('id', $id)
        ->restore();

    return \Redirect::route('accounts.index')
        ->with('message', 'Account restored!');
}
```

The route passes the ID properly. 

Anyone else had this issue? I have the equiv code working fine for MySQL and the inbuilt Illuminate SoftDelete.

**Comment by robsoncombr** [comment] 2017-04-29 09:03
Is this still an issue for you?
Does 'where('id', $id)' really returns an Object?
Have you tried with 'withTrashed()->where('id', $id)->restore()'?
If the problem is resolved, could you please close this?

**Closed** 2018-07-22 10:19 UTC
