### ISSUE TITLE
Performance Issue with over 2 million records 

### ISSUE THREAD

**Issue by venkeyRao** [jenssegers/laravel-mongodb#2061] opened 2020-07-09 14:58 UTC
- Laravel-mongodb Version: laravel: 5.7, jenssegers: 3.4
- PHP Version: 7.2
- Database Driver & Version:  mondodb: 3.4

simple queries like User::where('role', 'some_role')->where('name', 'some name')->orderBy('created_at', 'desc')->paginate(15); takes forver and time out occours with over 2 million records even after indexing the fields.
 
### Steps to reproduce
1. populate users collection with 25 lack records  
2. perform the above query
3. query puts a load on db server and queries start choking 

### Expected behaviour
Query should get executed, the same query, when changed to raw mongo query, and run on mongo shell, returns results in few milliseconds.   

### Actual behaviour
Query fails 

Question :
 
Is this package recommended for application with millions of users and has huge data? 
Kindly help here 

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ysb** [comment] 2020-07-09 19:24
What is the result when you run this query on mongodb server directly (without eloquent)?

**Comment by Smolevich** [comment] 2020-07-14 13:57
@venkeyRao can you give more context, if query fails with error, please describe error message?
Mongo is the local instance or cloud? Do you have problem with query `User::where('role', 'some_role')->where('name', 'some name')->orderBy('created_at', 'desc')->paginate(15)` ?

**Comment by elfeffe** [comment] 2020-07-14 21:48
Do you have the needed indexes?
I use this package with more than 70M documents, and it works.

**Comment by divine** [comment] 2021-01-08 18:23
Hello,

I've just had a chance to work with 520M of documents and everything works fine.

> Query should get executed, the same query, when changed to raw mongo query, and run on mongo shell, returns results in few milliseconds.

Run that in reverse. MongoDB caches the same queries and that's the only reason why it's being fast.

Also, you haven't given any information about your setup (sharded/replicas) and server information (can it handle fast so much information?).

Closing as it's not related / can't reproduce.

Thanks!

**Closed by divine** 2021-01-08 18:23 UTC
Labels: Needs investigation
