### ISSUE TITLE
Schema::rename error by migration

### ISSUE THREAD

**Issue by vingrad** [jenssegers/laravel-mongodb#1270] opened 2017-08-19 12:20 UTC
```
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 2 passed to Illuminate\Database\Schema\Blueprint::build() must be an instance of Illuminate\Database\Schema\Grammars\Grammar, null given, called in C:\OSPanel\domains\reporti
  ng-tool\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php on line 239
```

```
    public function up()
    {
        Schema::rename('reports_column_lists', 'databases');
        Schema::rename('reports_column_list_items', 'databaseItems');
        Schema::rename('reports_column', 'fields');
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
```

**Comment by alexgiuvara** [comment] 2017-08-19 13:07
duplicate of https://github.com/jenssegers/laravel-mongodb/issues/359

**Comment by vingrad** [comment] 2017-08-19 19:09
Laravel 5.4
> > php artisan migrate
> 
>   [Symfony\Component\Debug\Exception\FatalThrowableError]
>   Call to a member function prepare() on null

**Closed** 2020-02-16 10:28 UTC
Labels: question
