### ISSUE TITLE
I am getting the below error  I have connect my laravel script with mongodb  (1/1) ErrorException Trying to get property 'headers' of non-object  in VerifyCsrfToken.php line 158 at HandleExceptions->handleError(8, 'Trying to get property 'headers' of non-object',

### ISSUE THREAD

**Issue by stardesign77** [jenssegers/laravel-mongodb#1517] opened 2018-05-11 06:53 UTC
I am getting the below error

I have connect my laravel script with mongodb

(1/1) ErrorException Trying to get property 'headers' of non-object

in VerifyCsrfToken.php line 158 at HandleExceptions->handleError(8, 'Trying to get property 'headers' of non-object',

**Comment by divine** [comment] 2020-02-16 10:54
Duplicate of #1514

**Closed by divine** 2020-02-16 10:54 UTC
Labels: duplicate, question
