### ISSUE TITLE
Serialization of 'MongoDB\BSON\UTCDateTime' is not allowed

### ISSUE THREAD

**Issue by lukepolo** [jenssegers/laravel-mongodb#732] opened 2016-02-10 01:21 UTC
This is when im trying to store the results into a redis cache 

  return $this->returnAsRoles(\Cache::tags(Role::CACHE_TAG)->rememberForever('non_global_roles', function () {
            return Role::where('global_role', 0)->get()->toArray();
        }));

**Comment by lukepolo** [comment] 2016-02-10 01:25
Doing this will convert it from being an object to just a date string though 
  protected $dates = [
        'updated_at',
        'created_at'
    ];

**Comment by Hanccc** [comment] 2016-03-09 03:37
and it happen to the MongoDB\BSON\ObjectID too

**Comment by khoatran** [comment] 2016-03-18 08:05
Hi all, I have the same issue. Actually, this is not the problem of jenssegers/laravel-mongodb package. The root cause is inside MongoDB driver changes of their implementation.
Still waiting for their fix. However, I have figured out another way to pass by this issue. The general idea is: you need to implement your own serialize/deserialize yourself for your model. 

My solution: I create a custom Eloquent model which extend from Jenssegers\Mongodb\Eloquent\Model. Then, implements the \Serializable interface myself.  This is the gist which introduces my approach: [gist](https://gist.github.com/khoatran/45e0a54ce546d673d4d4)

In the above gist, I also try to detect whether the string is a 'serialised string' or not. The approach to detect this is implemented using exactly the same code with the 'is_serialized' method of Wordpress [here](https://core.trac.wordpress.org/browser/tags/4.4.2/src/wp-includes/functions.php#L0)

I hope this one is useful for everyone. I will refactor the gist to put into laravel mongodb package and make a pull request to fix this issue if the MongoDB team takes so long to fix this issue.

**Comment by Thedigit** [comment] 2016-03-23 21:51
Nice temp patch Khoatran. Having same issue currently i have solved it by not caching the _id at all and setting 
protected $dates = [
'updated_at',
'created_at'
];

hope they fix this at the monogdb lib level soon.

**Comment by deividaspetraitis** [comment] 2016-07-20 10:00
Fixed but not released yet as stable. However we can build from master manualy, worked like a charm. Reference: https://github.com/mongodb/mongo-php-library/issues/150

**Comment by jmikola** [comment] 2016-08-04 15:43
FYI: [1.2.0alpha1](https://github.com/mongodb/mongo-php-driver/releases/tag/1.2.0alpha1) has been released with the necessary BSON serialization features.

**Comment by lukepolo** [comment] 2016-08-04 15:52
Awesome news!

**Comment by xparthx** [comment] 2016-12-13 18:06
hey guys,

I'm also getting the same error:

**ErrorException in SerializableClosure.php line 117:
Serialization of closure failed: Serialization of 'MongoDB\BSON\UTCDateTime' is not allowed**

But I'm getting this with another package.

Please have a look to this:
https://github.com/jrean/laravel-user-verification/issues/94

Not sure, what is the exact issue is and with which package?

Any help would be appreciated.

Thanks,
Parth vora

**Comment by ebisbe** [comment] 2016-12-14 07:15
@xparthx have you read @khoatran message? It's all explained there. You can either wait for the new extension that will suport it, build your alpha extension or make a work arround with the code to convert Bson/OjectID and BSON/UTCDateTime to some plain string and during unserialization convert them again to each of their types.

**Comment by jmikola** [comment] 2016-12-14 16:13
@ebisbe: I replied in https://github.com/jrean/laravel-user-verification/issues/94#issuecomment-266818520, but the stable releases supporting serialization of BSON classes are [already available](https://pecl.php.net/package/mongodb). I assume @xparthx is still using 1.1.x.

**Comment by ebisbe** [comment] 2016-12-14 20:09
@jmikola thanks! I didn't know that the new connector was already available.

**Comment by xparthx** [comment] 2016-12-15 17:19
Thanks all of you for your time and effort. I have updated **PHP MongoDB extension** from 1.1.9 to 1.2.2 and fixed the bug.

**Closed** 2018-07-22 10:18 UTC
