### ISSUE TITLE
Call to a member function beginTransaction() on null

### ISSUE THREAD

**Issue by AravindhNextbrain** [jenssegers/laravel-mongodb#1931] opened 2020-01-30 07:57 UTC
Hi

I Am using Lumen 5.8 and jenssegers for MongoDB.. Eveything working fine except Excel import..
Using Laravel Excel Export version 3.0. Same working fine in laravel without jenssegers.

Whenever am Trying to use

Excel::import(new ExportClass,$file); Am getting **Call to a member function beginTransaction() on null** this exception.
Exception is : Call to a member function beginTransaction() on null

Please anyone provide the solution.

**Comment by divine** [comment] 2020-01-30 08:03
Hi,

Have you tried checking that library for issues in the first place?
This is a duplicate of 
https://github.com/Maatwebsite/Laravel-Excel/issues/1998 and should be closed.

Thanks.

**Closed** 2020-01-30 08:04 UTC

**Comment by AravindhNextbrain** [comment] 2020-02-04 07:50
Hi

Thanks for support, but still am facing same issue, as per this link Maatwebsite/Laravel-Excel#1998

Lumen Version : 5.8
PHP version: 7.2.26
maatwebsite/excel version: ^3.1
jenssegeres/mobodb: ^3.5


Is there any other solution..

For code sample, I just copied and tried with same code from this link  https://github.com/Maatwebsite/Laravel-Excel/issues/1998

**Comment by Smolevich** [comment] 2020-02-04 08:02
@AravindhNextbrain can you show code with error? You can PR [here](https://github.com/Smolevich/demo-mongo-application)

**Comment by AravindhNextbrain** [comment] 2020-02-04 08:12
Import Class

`<?php

namespace App\Imports;


use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\ToCollection;


class  TransactionImport implements ToCollection
{
    

    public function collection(Collection $rows)
    {       
        dd(['COLLECTION' => $rows]);

       
    }
}
`

In Controller ;
` try {
                Excel::import(new BankTransactionImport, $request->file);                
            } catch (\Maatwebsite\Excel\Validators\ValidationException $e) {
                $failures = $e->failures();
                return sendError($failures->errors(),'Valildator Errors',_Invalid());            
            }`

**Comment by Smolevich** [comment] 2020-02-04 08:20
@AravindhNextbrain itsn't full example

**Comment by w99910** [comment] 2021-03-07 05:47
I'm having this issue too. I have mongo database named 'mongoWork'.
### Version
` Laravel - 8.12`
` laravel-mongo - 3.8 `
` mongo version - 4.4 `
` maatwebsite/excel -3.1 `

### config/database.php 
`'mongodb' => [ `
 `           'driver' => 'mongodb',`
 `           'host' => env('DB_HOST', '127.0.0.1'),`
 `           'port' => env('DB_PORT', 27017),`
 `           'database' => env('DB_DATABASE'),`
 `           'username' => env('DB_USERNAME'),`
 `           'password' => env('DB_PASSWORD'),`
 `           'options' => [],`

### config/queue.php
 `connections'=>[ `
 `      database' => [`
 `           'driver' => 'mongodb',`
 `          'connection' => 'mongodb'`
 `          'table' => 'jobs',`
 `           'queue' => 'default',`
 `           'expire' => 60,]`
   `],`
`'failed' => [`
`        'driver' => 'mongodb',`
`        'database' => 'mongodb',`
`        'table' => 'failed_jobs',`
`    ],`

**I successfully created model User collection but when I tried to import excel, I got `Call to a member function beginTransaction() on null`**
**I tired `php artisan cache:clear` `php artisan config:clear` but still not working.**

### In Controller
`   try { `
       `   Excel::import(new ArticlesImport,\Storage::disk('public')->path('articles.xlsx'));`
     ` } catch (\Maatwebsite\Excel\Validators\ValidationException $e) {`
        ` Log::alert($e->failures());`
          ` }`
### ArticlesImport
`class ArticlesImport implements ToCollection`
`{`

`    public function collection(Collection $rows)`
`    {`
`            foreach($rows as $row){`
`                if($row[0]==='Factchecker'){`
`                    return null;`
`                }`
             `Article::create([`
`                    'title'=>$row[2]??'',`
`                     'created_at'=>Carbon::now(),`
`                ]); }`
`            }`

**Comment by Smolevich** [comment] 2021-03-07 08:53
> @Smolevich
> I'm having this issue too. I have mongo database named 'mongoWork'.
> 
> ### Version
> ` Laravel - 8.12`
> `laravel-mongo - 3.8`
> `mongo version - 4.4`
> `maatwebsite/excel -3.1`
> 
> ### config/database.php
> `'mongodb' => [ `
> ` 'driver' => 'mongodb',`
> ` 'host' => env('DB_HOST', '127.0.0.1'),`
> ` 'port' => env('DB_PORT', 27017),`
> ` 'database' => env('DB_DATABASE'),`
> ` 'username' => env('DB_USERNAME'),`
> ` 'password' => env('DB_PASSWORD'),`
> ` 'options' => [],`
> 
> ### config/queue.php
> `connections'=>[ `
> ` database' => [`
> ` 'driver' => 'mongodb',`
> ` 'connection' => 'mongodb'`
> ` 'table' => 'jobs',`
> ` 'queue' => 'default',`
> ` 'expire' => 60,]`
> `],`
> `'failed' => [`
> ` 'driver' => 'mongodb',`
> ` 'database' => 'mongodb',`
> ` 'table' => 'failed_jobs',`
> ` ],`
> 
> **I successfully created model User collection but when I tried to import excel, I got `Call to a member function beginTransaction() on null`**
> **I tired `php artisan cache:clear` `php artisan config:clear` but still not working.**
> 
> ### In Controller
> ` try {`
> ` Excel::import(new ArticlesImport,\Storage::disk('public')->path('articles.xlsx'));`
> ` } catch (\Maatwebsite\Excel\Validators\ValidationException $e) {`
> ` Log::alert($e->failures());`
> ` }`
> 
> ### ArticlesImport
> `class ArticlesImport implements ToCollection`
> `{`
> 
> ` public function collection(Collection $rows)`
> ` {`
> ` foreach($rows as $row){`
> ` if($row[0]==='Factchecker'){`
> ` return null;`
> ` }`
> `Article::create([`
> ` 'title'=>$row[2]??'',`
> ` 'created_at'=>Carbon::now(),`
> ` ]); }`
> ` }`

@w99910 look like misconfiguration, and please don't comment old closed issues, you can start new discussion or connect our slack channel
