### ISSUE TITLE
Laravel 4.2 and PHP 7

### ISSUE THREAD

**Issue by jubairsaidi** [jenssegers/laravel-mongodb#750] opened 2016-02-23 01:46 UTC
I have an app on Laravel 4.2.18 (slighly modified to work with PHP7 via [This Fork](https://github.com/jubairsaidi/laravel-framework-4.2.18-php7) (minor edit for the changes in ErrorHandling)

But the new system it's being migrated to is running PHP 7.  meaning I need to use the newer `pecl/mongodb`.  Any way I can continue using Laravel 4.2 with 3.0 of this package?  I don't mind forking if i have to, updating that app to laravel 5.x will take longer than what i have time for right now...

**Comment by GnarfDwarf** [comment] 2016-04-22 11:54
Same here

**Comment by logikinc** [comment] 2016-05-20 21:51
@jubairsaidi What ended up being your solution? I'm in the same situation at the moment. Thanks in advance!

**Comment by jubairsaidi** [comment] 2016-05-20 22:06
For now using postgres since I was using mongo for just one unstructured data component, so migrated over to a Postgres db table with a json field.  So not really a solution to this problem really if you rely heavily on mongo...

**Comment by logikinc** [comment] 2016-05-20 22:42
@jubairsaidi Yeah, not an option for me, I guess will have to wait until it's upgraded to 5.* >.< Thanks for a quick reply.

**Comment by Ardakilic** [comment] 2016-11-23 19:56
Laravel 4 now officially supports PHP7 with 4.2.20 and upwards updates, so I'm in the same boat with you guys

**Comment by Ardakilic** [comment] 2017-05-22 18:09
I have created a PR for this: https://github.com/jenssegers/laravel-mongodb/pull/1197 , please check. The fix requires an additional package, and may break compatibility with PHP versions lower than 5.5. I can confirm I can run Laravel 4.2 with PHP7 smoothly with the patch in the PR.

**Comment by ricardofontanelli** [comment] 2017-05-31 00:49
Hello @Ardakilic, would you know in what tag the PR #1197 was merged on branch 2.0? I'm trying to install these version using composer install but all tags of branch 2.0 doesn't include your changes.

**Comment by Ardakilic** [comment] 2017-05-31 06:38
@ricardoaponte try `dev-2.0` because there isn't a release of it yet.

**Comment by adiyodishreyas** [comment] 2017-08-22 11:53
Hi @Ardakilic dev-2.0 is not working. 
I am using this command:
composer require jenssegers/mongodb:dev-2.0

I get "package was not found" error. Am I missing something?
Is there any other way to install this change?

**Comment by Ardakilic** [comment] 2017-08-22 11:55
@adiyodishreyas Did you change minimum stability of your composer.json ? Try manually editing composer.json and try updating packages. May work.

**Comment by adiyodishreyas** [comment] 2017-08-22 12:05
@Ardakilic  thanks.
I changed the minimum stability to dev and used this command:
composer require jenssegers/mongodb:2.0.x-dev

**Closed** 2018-07-22 10:18 UTC
