### ISSUE TITLE
Which mongo db extension version i should have to add for PHP7 please explain and mention this in more detail

### ISSUE THREAD

**Issue by stardesign77** [jenssegers/laravel-mongodb#1511] opened 2018-05-05 14:46 UTC
Which mongo db extension version i should have to add for PHP7 please explain and mention this in more detail

**Comment by divine** [comment] 2020-02-16 10:53
Duplicate of https://github.com/jenssegers/laravel-mongodb/issues/1514

**Closed by divine** 2020-02-16 10:53 UTC
Labels: duplicate, question
