### ISSUE TITLE
[v2.2.2][password reminder] other than MongoDate, DatabaseTokenRepository should also take care of array type.

### ISSUE THREAD

**Issue by wppd** [jenssegers/laravel-mongodb#610] opened 2015-10-05 03:30 UTC
laravel: 5.1.19
laravel-mongodb: v2.2.2

When I was using `Illuminate\Auth\Passwords\PasswordResetServiceProvider`, it yields error. 

So, I try `Jenssegers\Mongodb\Auth\PasswordResetServiceProvider` to replace the laravel's,  same error.

`ErrorException in DatabaseTokenRepository.php line 126: strtotime() expects parameter 1 to be string, array given`

`
  ["created_at"]=>
  array(3) {
    ["date"]=>
    string(26) "2015-10-05 02:51:23.000000"
    ["timezone_type"]=>
    int(3)
    ["timezone"]=>
    string(3) "UTC"
  }
`

In mongodb's DatabaseTokenRepository, I find out it will cast MongoDate only.

it's weird that you did cast array type in the older version, at least in v2.0.5.

**Comment by darkin1** [comment] 2015-10-08 21:04
LV 5.1, Moloquent: 2.1 - confirmed

**Comment by wuori** [comment] 2015-12-03 15:36
Fixed with #663

**Comment by zeroonnet** [comment] 2015-12-22 22:14
I still have this issue.

I added the provider to the config.php but it still displays the same error "strtotime() expects parameter ....."

The code never gets inside the "DatabaseTokenRepository.php" that comes on this package, it's always including the "\Illuminate\Auth\Passwords\DatabaseTokenRepository" by default.

**Comment by adriantombu** [comment] 2016-01-29 10:44
Same problem here, goes here

`vendor/laravel/framework/src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php line 126`

**Comment by wuori** [comment] 2016-01-29 15:00
@adriantombu @zeroonnet Which versions of Laravel are you using? There's an issue with 5.2 that has not been resolved yet with Auth.

**Comment by adriantombu** [comment] 2016-01-29 15:07
I'm on the 5.2, so looks like I'll have to wait then ^_^

**Comment by wuori** [comment] 2016-01-29 15:16
@adriantombu Temp fix is in #694. I'm hoping to look into this soon if nobody else has by then.

**Comment by jaffar-citytwig** [comment] 2016-02-03 07:22
> I'm on the 5.2, so looks like I'll have to wait then ^_^

i am having same issue

**Comment by darkin1** [comment] 2016-08-24 08:01
Laravel 5.2.*
Jessenger: 3.0.*
PHP 7

For fixing Password Reset case, only what you need to do it's to change Provider for Reset Password

`Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,`

to 

`Jenssegers\Mongodb\Auth\PasswordResetServiceProvider::class,`

After that `created_at` will be convert from array to MongoDate and you will not get the `Type error: DateTime::__construct() expects parameter 1 to be string, array given` error.

@jenssegers Maybe could you add this to the documentation? 

Cheers ;)

**Comment by abhijeetkumar** [comment] 2016-11-24 09:05
@darkin1 Hey thanks a lot buddy.... It's working for me now.... :+1:

**Comment by LaGgY-Eval** [comment] 2017-01-05 14:44
php: 5.5.9
laravel/framework: 5.2
jenssegers/mongodb : 2.2

Same issue, have tried what @darkin1 stated above, still receiving the exception.

**Comment by k-zakhariy** [comment] 2017-01-06 15:51
@darkin1 Thanks, you saved my day!!!!
php 5.6
Laravel 5.3
jenseegers/mongodb: ~3.0

**Closed** 2018-07-22 10:18 UTC

**Comment by mcandylab** [comment] 2019-03-07 15:13
In Config/App.php replace `Illuminate\Auth\Passwords\PasswordResetServiceProvider` on `Jenssegers\Mongodb\Auth\PasswordResetServiceProvider`
In App/Http/Controllers/Auth/ResetPasswordController.php add `use MongoDB\BSON\UTCDateTime; `

Timezone: Europe/Moscow
Laravel: 5.7.*
Jenssegers/mongodb: "^3.4"
