### ISSUE TITLE
[Feature Request] Configuration for relation keys types needed

### ISSUE THREAD

**Issue by pervozdanniy** [jenssegers/laravel-mongodb#2167] opened 2020-12-25 14:42 UTC
### Is your feature request related to a problem?
I have an 1-to-1 relation for 2 tables with foreign key saved as `ObjectId`:
Sales:
  ```js
{
   _id: ObjectId("some_id")
   idUser: ObjectId("foreignKey")
    ...otherFields
}
  ```
Users:
```js
{
   _id: ObjectId("foreignKey"),
   ...otherFileds
}
```
Relation is defined on Sales model as follows:
```php
public function user(): BelongsTo
{
     return $this->belongsTo(User::class, 'idUser', '_id', 'user');
}
```

When I'm trying to apply whereHas condition:
```php
$query->whereHas('user', static fn (Builder $query): Builder => $query->where('username', $keyword));
```
it returns no results for relation fetching query (from laravel debugger):
```
users.find({"username":"enegy5"},{"projection":{"_id":true},"typeMap":{"root":"array","document":"array"}})
sales.find({"idUser":{"$in":["5f5d18344504d801ea0a1b23"]}},{"sort":{"dateCreate":-1},"limit":10,"typeMap":{"root":"array","document":"array"}})
```
while Sale document with such idUser does exist.
 
### Describe the solution you'd like
I'd like to have an configuration array for each model extended from `Jenssegers\Mongodb\Eloquent\Model` to have an ability to somehow say if I need an `ObjectId` or a `string` format of foreign key, e.g.

```php
protected $relatedKeyTypes = [
   'idUser' => 'objectId',
   'showroomId' => 'string'
];
```
which should be applied to `Jenssegers\Mongodb\Helpers\QueriesRelationships::getConstrainedRelatedIds()` method

**Comment by divine** [comment] 2020-12-26 11:53
Duplicate of https://github.com/jenssegers/laravel-mongodb/issues/2040, see also https://github.com/jenssegers/laravel-mongodb/issues/1974#issuecomment-592857370

**Closed by divine** 2020-12-26 11:53 UTC
